version: '2.4'
services:
        myfirstserver:
                      container_name: server
                      command: python3 -m http.server 1234
                      ports:
                          - 1234:1234
                      build:
                          context: .
                          dockerfile: Dockerfile